### ISSUE TITLE
Dark menu bar is missing

### ISSUE THREAD

**Issue by zelid** [ysc3839/win32-darkmode#1]
I've downloaded master version on 19-July-2019 and everything looks good (submenus, popups, titlbar, scrollbars) all beside menu.

![menu](https://user-images.githubusercontent.com/179463/59785550-b7bbcd00-92cd-11e9-838b-3217ffe70a05.png)

Windows Explorer has dark menu.
How to use the same dark menu styling as Windows Explorer has?

**Comment by ysc3839** [comment]
Windows Explorer does not have dark menu, that is Ribbon UI with dark theme.
It seems that Windows does not provide dark menu bar, so I can't solve this issue.

**Comment by tom-huntington** [comment]
Was going to ask you to do a dark themed UI but then I realized choosing the color was built in to the ribbon framework.

Just for my curiosity, how did you learn the undocumented API?

**Comment by ysc3839** [comment]
@tom-huntington Using IDA and x64dbg to decompile system executables.
