### ISSUE TITLE
When cloning this sample and building the existing code the initial window is white

### ISSUE THREAD

**Issue by Skewjo** [ysc3839/win32-darkmode#13]
My apologies for posting this issue without doing a bit of troubleshooting. I've been attempting to implement/research how to create a dark mode for my app for 3 days and have been mostly unsuccessful.

When I clone, build, and run this project the window appears to be the default Window color.
![image](https://user-images.githubusercontent.com/4118039/101651755-064db180-3a03-11eb-934e-4b4176345a84.png)

Is this sample just using some pre-defined theme that I have to have changed in my Windows user settings or something similar?
Or have I maybe built it incorrectly?

![image](https://user-images.githubusercontent.com/4118039/101652017-5462b500-3a03-11eb-855a-05afe6882d10.png)

**Comment by ysc3839** [comment]
Did you turn on dark mode in Settings?

**Comment by Skewjo** [comment]
From a settings menu in the dialog box, or a Windows setting? Because there doesn't appear to be a dark mode setting inside of the dialog box.

**Comment by ysc3839** [comment]
Windows Settings.
