### ISSUE TITLE
How to make menubar dark?

### ISSUE THREAD

**Issue by kitepad** [ysc3839/win32-darkmode#14]
I build demo using vs 2019 community and test it on win 10 (buildnumber = 19042, add it as supported).
Test result is ok for demo excerpt menubar are light , menu items are darked.

Because of we don't have 19041 env, is it same light in 19041? If yes, how to make it dark?

**Comment by ysc3839** [comment]
Because Microsoft doesn't provide a dark menu bar. The only way to make it dark is to owner draw.

**Comment by adzm** [comment]
I actually figured out how to custom draw the menubar even with themes enabled, using some undocumented window messages and structures, but this whole project is that so I imagine that part is not a problem. https://github.com/adzm/win32-custom-menubar-aero-theme

**Comment by adzm** [comment]
Also PR #17 adds this to the sample application
