### ISSUE TITLE
No Worky

### ISSUE THREAD

**Issue by SimonG4ELI** [ysc3839/win32-darkmode#18]
Hi All,

I consider myself to be a most knowledgeable developer, but for the life of me on Windows 10 19041 (2004) with VS2019 despite all checks succeeding the demo app does not show dark mode.

- Download code
- Compile code
- Run code
- Black text on a white background

Clearly I'm missing something, checked brain still screwed on and it is!

All advice and insults welcomed :) .

**Comment by ysc3839** [comment]
Did you enable dark mode for apps in Settings?

**Comment by SimonG4ELI** [comment]
> Did you enable dark mode for apps in Settings?

Thanks, that was the info I needed.
