### ISSUE TITLE
Windows 11?

### ISSUE THREAD

**Issue by God-damnit-all** [ysc3839/win32-darkmode#19]
Did Windows 11 break any of this functionality in any way?

**Comment by rounk-ctrl** [comment]
No, not really

**Comment by DRSDavidSoft** [comment]
In `DarkMode.h` file and function `InitDarkMode()`, there is an if condition that explicitly checks for Windows 10 and some build numbers. You have to remove it or modify it to work on Windows 10, otherwise it says "Dark mode is not supported".

**Update:** I found #23
