### ISSUE TITLE
Dark mode is not supported

### ISSUE THREAD

**Issue by 0xF5T9** [ysc3839/win32-darkmode#20]
Hi, I'm sorry if this is a dump question.
why it said "Dark mode is not supported" when I call InitDarkMode(), it happen even on the original code.
Is it has anything to do with my SDK version, am I missing something? Thank you
EDIT: I compiling the project with latest SDK & VS 2022

**Comment by ysc3839** [comment]
It checks Windows build number to prevent issues when running on a newer system. https://github.com/ysc3839/win32-darkmode/blob/cc26549b65b25d6f3168a80238792545bd401271/win32-darkmode/DarkMode.h#L179-L185 You should temporary remove that check and test if it working fine on new system, and then add build number to that list. Or you can completely remove the check, but it may cause issues if Microsoft changes these APIs on newer system.

**Comment by 0xF5T9** [comment]
Thank you so much!
