### ISSUE TITLE
How to disable selection in Child Windows or some area in this program

### ISSUE THREAD

**Issue by kumo-rn5s** [ysc3839/win32-darkmode#4]
I'am afraid that I don't need selection in somewhere. I searched in every Internet but i didn't find it.
If you know, can you tell me about that?

**Comment by ysc3839** [comment]
What is selection?

**Comment by AraHaan** [comment]
@ysc3839 it is when you select an item in a listview, etc, or even selecting text in a textbox of some sort.

But also when you hover over menu items as well the same color is usually used by windows for all of that.
